// <auto-generated />
namespace Datavail.Delta.Cloud.Datawarehouse.Worker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddDimDates : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201202081435166_AddDimDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so6dZm11mRTl+mpdtNj4pq/VsjA+vsjqfV+smH3+3qt/m9UfpcVlkhODrvDx/T2x3HgLbjywehMkpYdxev7le5YwNIVIsqNvcb0TNfq/8OviAPnpZV6u8bq9f5efmVXqPGn6U3g1fvtt9277bfRF4fPbR2bK9t/dR+mJdltmkpA/Os7LJP0pXnz563VZ1/nm+zGt6ZfYya9u8pol7US1zpcWj1ae3I8fDuzt7IMfdbLms2qwlDuhh3sPz+svz7+b5W4Pp67YmjvoofVa8y2fP8+VFO7fYfpG9M5/Qrx+lXy0LYkB6qa3XuT86+Xtzz+j0SX5RLHlutHf8/ob4LUKqm6G9WC8m4KbNJN8M54tq2c6/OUAZhvJDJqzt+fW8qtufm+5Pl7NvZFqJPZuzJYP8sOn4ffKs/gbA/MQ6q0k+vwkGMaB+LlgE1Pgw7M8aSFy+nBkwT6qqzLPl1wFERmCWWVX5dQEpPl/W+MWD90Mj6lnz7aosvoGRKJgfAmc8vuuMZd+EkrFvs4IMkxFG2PGnV/g4f9d2zKm88jpvQ6PbfJS6LsTCj409jqJiO3WuxV3xLYwPcnfACXn8RbZaEZU8p0Q/SV+LR3Ky/fr93YuFwLg7bSJehsXW9kTWPLvIO99S14Tps6JuWjhAkwzzdjJb9JrdjsSmsw6lu+6MI7x5Ab9b/+R2zpmdrQ50R91nNOBFvmx57DpyQnLA79J3X0+zMquHnKaTqlwvlhtdsM1wrFMTQrIf3x5Wx03x4XW+ej+YxoR0AZrPbw8tcFl8cMEX7wuPlU8fGn/8NWCpLxIFqN+9J1TrYvRg2m9uDzHwMzo84764PTzP3fCheR/fHlbH5/Dhdb56f5i9WQ6+uD08cSi6Q30fCJ5D4YPxPn4vWMan6MAyH98eVt+t6Eps+O3tIXv+Qoil/fj2sAKXwYcWfNGH9/huR4l3bYjnIGjL0Cbp984obTLp3Sa2d2vaOyb8sZrTm5MNPfsqTT5KiVCXxQy29fV10+YLNnLj17+oPCkLGq9r8EW2LM7zpn1T0YxS4oTM/9dPTNhIvGlm5f/rsxMF6PCeTmovcbC8zOrpPKu3Ftm7O+/rO0eTATP6Hcmn98atnwz4OiOMpAK+PhiWv2+AUPHg/sNBdgL2r036SMD+dYjWC9e/DpBosP4hgL6pSfTD76+DTy/4nhRfC0gYeH8dIENB9weRpxdIfx3MIkH0eyD1foFxP7gLURuIjTeFxmK+SBAn1UfpG0HThdQxVG8ROPet6eO7foL/8dO8KS4cCKT7l/kUeWQH1LQ5W55XhuY0NB8j06SraPI2I8WSHddtcZ5NW/p6mjcNJzZ+MivX1OSURHV2tvxy3a7W7XHT5ItJGdi3x3c398/ZgRDnx1+u8JfnPnz9IRCaBXTjl8sn66KcWbyf9VlyCASYRdP9hBUldgjcxbWFJHn/2wBS8j3NVySB5Mq8yRerEvzx5fJ1dpkP43YzDUOKPX5aZBd1tvApKJ8oJq8z6tnrgjrw33D90Z/ErrS6dPT/BAAA//9mIZo20hoAAA=="; }
        }
    }
}
