// <auto-generated />
namespace Datavail.Delta.Datawarehouse.Processor.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddServerDimension : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204172304088_AddServerDimension"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVYzW7bRhC+F+g7EDy1h4iKCwSJQSVQJDsVWtmB6fq+IkfSovvD7C5t6dl66CP1FTpL8Z+yRJqBgdzI4e43387ufjPD//751/+048x5BKWpFBP37WjsOiBCGVGxmbiJWb957376+PNP/lXEd85DPu7CjsOZQk/crTHxpefpcAuc6BGnoZJars0olNwjkfQuxuP33tuxBwjhIpbj+HeJMJRD+oKvMylCiE1C2FJGwHRmxy9BiurcEA46JiFM3Dkx5JFQNpoDM2RkX5+Igq1MNIy+KhmC1lK5zpRRguwCYOueVMcfLFW3IIE0rpCu2d/vY0ipWFiFQauOwVF/wL5mQBMSikGZ/R2sazNxqOt49elec34xuz3VUpm4C2F+u3Cdm4QxsmJoWBOmwXXid5eBkQq+gABFDERfiTGgcOMWEaRLyUJyGb/rFpUP3vjCRsUjQkhDDJ6CFv+jbBdRTvZLQqMjXE+DzBJtJO+06G5AA/lMNxi/7BrkQIFReFtc55ruIPoTxMZsC7Ql2eUWfHSdvwTFy4WTjEqg6v3wftr571IbgU+v7ngRT6NI4cV6fc/6gSorDLnnz1IyIKL3xgV4aJPX538nn9CzMrljlCu4pxx680egKxENhlloBJolSuEx7hdS3ytFsC2NqOCGUFSbzE8qzvMna4adaejkYUoApqYUuDmlh4NwjzKZPUqkcFlmC++QLvK04j2TV/wliWPc/0qeySxOcEgyszdB/6TBDxheqI/kjoJt4QkFmmyg8RVdI9NrqrSxmW1F7DbMIt4a1i3AubN6nJtJqgx7Pt4+ZxvZKd2OjuXDamCvca0cz1y6bCj4HU+k2dQgJIyo53PgTLKEizNZ9TyWzQhtKGvtjlRLU1Ww2of+eE1uVXt3tHrSquLVv3RHLDNRFa20dkeqpJYqVMXcA6tMFjWs0tzjbGT5onYyMlt3lFL+qziltRdSqv8NnNTWJ0JV+a8Hqfqljeh7jZvc"
                       + "FBGvpSKN6rYpSqckvTmk8F5Ie0PC/UxOz/cPLX09DHEdDNUjjay2BnttgKdaNwq+sRmjaVDyAUsi6Bq0uZd/g+2FUP5f3m4UhbXWEfsReg5qQ3G2u+hbnTV6hUTQbwnQFG5NbQUwvG9IiQ/uGgYzO9ZBiEeiwi1Rv3Cy+3VoVzAIrFXpD0NrVu8r2n8P6pX7ID7NajzC02uGV+MvhjlWjZ8PUb9KvF1PdinGT9TiB73EVa8kcj6wnFNeFPEvrNXbAu571d9E/hw03ZQQ9qeRgND+iShB8zELsZZ5rHFpVUb5kMZWLMEQ3EcyVXivSWiy0jbtEh8IS3DIFV9BtBC3iYkTM9Ua+IrVFNX3TvtPG5I6Z/82tm/6eywBaVJ7FG/F54SyqOB9feQIPQNhD0sm68gKu2SE2+wLpBspOgJl4ZtDDMJq5T3wmCGYvhUBeYTnuZ2PYT1i/pySjSJcZxjlfPvX0rO/LT/+D1ERY+HoFAAA"; }
        }
    }
}
