//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datavail.Delta.Agent.Plugin.CheckIn.CheckInServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckInServiceProxy.ICheckInService")]
    public interface ICheckInService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckInService/CheckIn", ReplyAction="http://tempuri.org/ICheckInService/CheckInResponse")]
        bool CheckIn(System.DateTime timestamp, System.Guid tenantId, System.Guid serverId, string hostname, string ipAddress, string agentVersion, System.Nullable<System.Guid> customerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckInServiceChannel : Datavail.Delta.Agent.Plugin.CheckIn.CheckInServiceProxy.ICheckInService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckInServiceClient : System.ServiceModel.ClientBase<Datavail.Delta.Agent.Plugin.CheckIn.CheckInServiceProxy.ICheckInService>, Datavail.Delta.Agent.Plugin.CheckIn.CheckInServiceProxy.ICheckInService {
        
        public CheckInServiceClient() {
        }
        
        public CheckInServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckInServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckInServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckInServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckIn(System.DateTime timestamp, System.Guid tenantId, System.Guid serverId, string hostname, string ipAddress, string agentVersion, System.Nullable<System.Guid> customerId) {
            return base.Channel.CheckIn(timestamp, tenantId, serverId, hostname, ipAddress, agentVersion, customerId);
        }
    }
}
