//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datavail.Delta.Infrastructure.Agent.UpdateServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateServiceProxy.IUpdateService")]
    public interface IUpdateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/GetAssembly", ReplyAction="http://tempuri.org/IUpdateService/GetAssemblyResponse")]
        byte[] GetAssembly(System.Guid serverId, string assembly, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/GetAssemblyList", ReplyAction="http://tempuri.org/IUpdateService/GetAssemblyListResponse")]
        System.Collections.Generic.Dictionary<string, string> GetAssemblyList(System.Guid serverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/GetConfig", ReplyAction="http://tempuri.org/IUpdateService/GetConfigResponse")]
        string GetConfig(System.Guid serverId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateServiceChannel : Datavail.Delta.Infrastructure.Agent.UpdateServiceProxy.IUpdateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateServiceClient : System.ServiceModel.ClientBase<Datavail.Delta.Infrastructure.Agent.UpdateServiceProxy.IUpdateService>, Datavail.Delta.Infrastructure.Agent.UpdateServiceProxy.IUpdateService {
        
        public UpdateServiceClient() {
        }
        
        public UpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetAssembly(System.Guid serverId, string assembly, string version) {
            return base.Channel.GetAssembly(serverId, assembly, version);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetAssemblyList(System.Guid serverId) {
            return base.Channel.GetAssemblyList(serverId);
        }
        
        public string GetConfig(System.Guid serverId) {
            return base.Channel.GetConfig(serverId);
        }
    }
}
